### ISSUE TITLE
Images don't seem to be loading (404 errors) in Heroku

### ISSUE THREAD

**Issue by mhtien** [fac20/week-5-ELMP#36]
Works when you clone it but on heroku it doesnt load.
Main page and the /form url shows the type its getting is text/html in the console
When you hover over the file - the url is as below. Maybe your public handler is not picking it up because the url of this doesn't include "public"? might have to check why public isnt showing up or add .includes("images")

![image](https://user-images.githubusercontent.com/59407030/90236135-44064900-de1a-11ea-88d7-2db0678b1d43.png)

Not sure if this is helpful..

**Comment by glrta** [comment]
On my local I solved it including:
- `/public/image...etc` in the file paths in the HTML files. 
- `const publicHandler = require("./public")` at the top in the router file
=D
